set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)

# LibXR
set(LIBXR_SYSTEM freertos)
set(LIBXR_DRIVER st)
set(XROBOT_WORKSPACE_DIR ${CMAKE_CURRENT_SOURCE_DIR}/../..)
set(XROBOT_MODULES_DIR ${XROBOT_WORKSPACE_DIR}/Modules)
set(XROBOT_USER_DIR ${XROBOT_WORKSPACE_DIR}/User)
file(GLOB XROBOT_MODULE_DIRS LIST_DIRECTORIES true "${XROBOT_MODULES_DIR}/*")
add_subdirectory(Middlewares/Third_Party/LibXR)
target_link_libraries(xr
    PUBLIC stm32cubemx
)

target_include_directories(xr
    PUBLIC $<TARGET_PROPERTY:stm32cubemx,INTERFACE_INCLUDE_DIRECTORIES>
    PUBLIC Core/Inc
    PUBLIC User
    PUBLIC ${XROBOT_USER_DIR}
)

foreach(module_dir IN LISTS XROBOT_MODULE_DIRS)
    if(IS_DIRECTORY "${module_dir}")
        target_include_directories(xr PUBLIC "${module_dir}")
    endif()
endforeach()

# Add include paths
target_include_directories(${CMAKE_PROJECT_NAME} PRIVATE
    # Add user defined include paths
    PUBLIC $<TARGET_PROPERTY:xr,INTERFACE_INCLUDE_DIRECTORIES>
    PUBLIC User
    PUBLIC ${XROBOT_USER_DIR}
)

# Add linked libraries
target_link_libraries(${CMAKE_PROJECT_NAME}
    stm32cubemx

    # Add user defined libraries
    xr
)

file(
    GLOB LIBXR_USER_SOURCES "${CMAKE_CURRENT_SOURCE_DIR}/User/*.cpp")

if(EXISTS "${CMAKE_CURRENT_SOURCE_DIR}/App/CMakeLists.txt")
    add_subdirectory(App)
endif()

target_sources(${CMAKE_PROJECT_NAME}
    PRIVATE ${LIBXR_USER_SOURCES}
)

if(CMAKE_BUILD_TYPE STREQUAL "Debug")
    target_compile_options(${CMAKE_PROJECT_NAME} PRIVATE -Og)
    target_compile_options(xr PRIVATE -O2)
    if(TARGET FreeRTOS)
        target_compile_options(FreeRTOS PRIVATE -O2)
    endif()

    if(TARGET STM32_Drivers)
        target_compile_options(STM32_Drivers PRIVATE -O2)
    endif()

    if(TARGET USB_Device_Library)
        target_compile_options(USB_Device_Library PRIVATE -O2)
    endif()
endif()
